[package]
name = "llmrs-dev"
version = "0.1.0"
edition = "2024"

[features]
default = []
cuda = []     # compile cuda/*.cu
bf16 = []
fp16 = []

[dependencies]
cust = "0.3.2"
half = "2.6.0"
rand = "0.9.2"
bytemuck = "1.14"

[build-dependencies]
cc = "1.2"
