[build]
rustflags = [
  "-C", "opt-level=3",           # Highest optimization, roughly -O3
  "-C", "target-cpu=native",     # Use all instructions for local CPU, like -march=native
  "-C", "embed-bitcode=yes"

]
