name: Build and test

on:
  create:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Cancel previous runs for the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  # --- CPU-only tests on all OSes (no CUDA) ---
  cpu-tests:
    name: CPU tests (${{ matrix.os }} / ${{ matrix.toolchain }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      # fmt & clippy
      - name: rustfmt --check
        run: cargo fmt --all -- --check
      - name: clippy (workspace)
        run: cargo clippy --workspace --all-targets -- -D warnings

      # Build & test
      - name: Build (no features)
        run: cargo build --workspace --locked
      - name: Test (no features)
        run: cargo test --workspace --all-targets --locked
